[theme]
base = "dark"
primaryColor = "#22D3EE"
backgroundColor = "#090B10"
secondaryBackgroundColor = "#11151B"
textColor = "#F4F7FA"
font = "sans serif"

[server]
headless = true
maxUploadSize = 200

